// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ingenuity.salesquote.domain;

import com.ingenuity.salesquote.domain.Quote;
import com.ingenuity.salesquote.domain.QuoteDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect QuoteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QuoteDataOnDemand: @Component;
    
    private Random QuoteDataOnDemand.rnd = new SecureRandom();
    
    private List<Quote> QuoteDataOnDemand.data;
    
    public Quote QuoteDataOnDemand.getNewTransientQuote(int index) {
        Quote obj = new Quote();
        setCustomer(obj, index);
        setDiscount(obj, index);
        setQuotedate(obj, index);
        setSalesrep(obj, index);
        return obj;
    }
    
    public void QuoteDataOnDemand.setCustomer(Quote obj, int index) {
        String customer = "customer_" + index;
        obj.setCustomer(customer);
    }
    
    public void QuoteDataOnDemand.setDiscount(Quote obj, int index) {
        int discount = index;
        obj.setDiscount(discount);
    }
    
    public void QuoteDataOnDemand.setQuotedate(Quote obj, int index) {
        Date quotedate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setQuotedate(quotedate);
    }
    
    public void QuoteDataOnDemand.setSalesrep(Quote obj, int index) {
        String salesrep = "salesrep_" + index;
        obj.setSalesrep(salesrep);
    }
    
    public Quote QuoteDataOnDemand.getSpecificQuote(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Quote obj = data.get(index);
        Long id = obj.getId();
        return Quote.findQuote(id);
    }
    
    public Quote QuoteDataOnDemand.getRandomQuote() {
        init();
        Quote obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Quote.findQuote(id);
    }
    
    public boolean QuoteDataOnDemand.modifyQuote(Quote obj) {
        return false;
    }
    
    public void QuoteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Quote.findQuoteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Quote' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Quote>();
        for (int i = 0; i < 10; i++) {
            Quote obj = getNewTransientQuote(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
