// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ingenuity.salesquote.domain;

import com.ingenuity.salesquote.domain.QuoteIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect QuoteIntegrationTest_Roo_Configurable {
    
    declare @type: QuoteIntegrationTest: @Configurable;
    
}
