// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ingenuity.salesquote.domain;

import com.ingenuity.salesquote.domain.SalesOrder;
import com.ingenuity.salesquote.domain.SalesOrderDataOnDemand;
import com.ingenuity.salesquote.domain.SkuDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SalesOrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SalesOrderDataOnDemand: @Component;
    
    private Random SalesOrderDataOnDemand.rnd = new SecureRandom();
    
    private List<SalesOrder> SalesOrderDataOnDemand.data;
    
    @Autowired
    private SkuDataOnDemand SalesOrderDataOnDemand.skuDataOnDemand;
    
    public SalesOrder SalesOrderDataOnDemand.getNewTransientSalesOrder(int index) {
        SalesOrder obj = new SalesOrder();
        setQuanity(obj, index);
        return obj;
    }
    
    public void SalesOrderDataOnDemand.setQuanity(SalesOrder obj, int index) {
        int quanity = index;
        obj.setQuanity(quanity);
    }
    
    public SalesOrder SalesOrderDataOnDemand.getSpecificSalesOrder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SalesOrder obj = data.get(index);
        Long id = obj.getId();
        return SalesOrder.findSalesOrder(id);
    }
    
    public SalesOrder SalesOrderDataOnDemand.getRandomSalesOrder() {
        init();
        SalesOrder obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SalesOrder.findSalesOrder(id);
    }
    
    public boolean SalesOrderDataOnDemand.modifySalesOrder(SalesOrder obj) {
        return false;
    }
    
    public void SalesOrderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SalesOrder.findSalesOrderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SalesOrder' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SalesOrder>();
        for (int i = 0; i < 10; i++) {
            SalesOrder obj = getNewTransientSalesOrder(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
