// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ingenuity.salesquote.domain;

import com.ingenuity.salesquote.domain.SalesOrder;
import com.ingenuity.salesquote.domain.SalesOrderDataOnDemand;
import com.ingenuity.salesquote.domain.SalesOrderIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SalesOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SalesOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SalesOrderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SalesOrderIntegrationTest: @Transactional;
    
    @Autowired
    private SalesOrderDataOnDemand SalesOrderIntegrationTest.dod;
    
    @Test
    public void SalesOrderIntegrationTest.testCountSalesOrders() {
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", dod.getRandomSalesOrder());
        long count = SalesOrder.countSalesOrders();
        Assert.assertTrue("Counter for 'SalesOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SalesOrderIntegrationTest.testFindSalesOrder() {
        SalesOrder obj = dod.getRandomSalesOrder();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to provide an identifier", id);
        obj = SalesOrder.findSalesOrder(id);
        Assert.assertNotNull("Find method for 'SalesOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SalesOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SalesOrderIntegrationTest.testFindAllSalesOrders() {
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", dod.getRandomSalesOrder());
        long count = SalesOrder.countSalesOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'SalesOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SalesOrder> result = SalesOrder.findAllSalesOrders();
        Assert.assertNotNull("Find all method for 'SalesOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SalesOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SalesOrderIntegrationTest.testFindSalesOrderEntries() {
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", dod.getRandomSalesOrder());
        long count = SalesOrder.countSalesOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SalesOrder> result = SalesOrder.findSalesOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SalesOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SalesOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SalesOrderIntegrationTest.testFlush() {
        SalesOrder obj = dod.getRandomSalesOrder();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to provide an identifier", id);
        obj = SalesOrder.findSalesOrder(id);
        Assert.assertNotNull("Find method for 'SalesOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySalesOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SalesOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SalesOrderIntegrationTest.testMergeUpdate() {
        SalesOrder obj = dod.getRandomSalesOrder();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to provide an identifier", id);
        obj = SalesOrder.findSalesOrder(id);
        boolean modified =  dod.modifySalesOrder(obj);
        Integer currentVersion = obj.getVersion();
        SalesOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SalesOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SalesOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", dod.getRandomSalesOrder());
        SalesOrder obj = dod.getNewTransientSalesOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SalesOrder' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SalesOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SalesOrderIntegrationTest.testRemove() {
        SalesOrder obj = dod.getRandomSalesOrder();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SalesOrder' failed to provide an identifier", id);
        obj = SalesOrder.findSalesOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SalesOrder' with identifier '" + id + "'", SalesOrder.findSalesOrder(id));
    }
    
}
