// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ingenuity.salesquote.domain;

import com.ingenuity.salesquote.domain.CategoryDataOnDemand;
import com.ingenuity.salesquote.domain.Sku;
import com.ingenuity.salesquote.domain.SkuDataOnDemand;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SkuDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SkuDataOnDemand: @Component;
    
    private Random SkuDataOnDemand.rnd = new SecureRandom();
    
    private List<Sku> SkuDataOnDemand.data;
    
    @Autowired
    private CategoryDataOnDemand SkuDataOnDemand.categoryDataOnDemand;
    
    public Sku SkuDataOnDemand.getNewTransientSku(int index) {
        Sku obj = new Sku();
        setName(obj, index);
        setPrice(obj, index);
        setTerm(obj, index);
        return obj;
    }
    
    public void SkuDataOnDemand.setName(Sku obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void SkuDataOnDemand.setPrice(Sku obj, int index) {
        BigDecimal price = BigDecimal.valueOf(index);
        obj.setPrice(price);
    }
    
    public void SkuDataOnDemand.setTerm(Sku obj, int index) {
        int term = index;
        obj.setTerm(term);
    }
    
    public Sku SkuDataOnDemand.getSpecificSku(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Sku obj = data.get(index);
        Long id = obj.getId();
        return Sku.findSku(id);
    }
    
    public Sku SkuDataOnDemand.getRandomSku() {
        init();
        Sku obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Sku.findSku(id);
    }
    
    public boolean SkuDataOnDemand.modifySku(Sku obj) {
        return false;
    }
    
    public void SkuDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Sku.findSkuEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Sku' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Sku>();
        for (int i = 0; i < 10; i++) {
            Sku obj = getNewTransientSku(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
