// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ingenuity.salesquote.domain;

import com.ingenuity.salesquote.domain.Sku;
import com.ingenuity.salesquote.domain.SkuDataOnDemand;
import com.ingenuity.salesquote.domain.SkuIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SkuIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SkuIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SkuIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SkuIntegrationTest: @Transactional;
    
    @Autowired
    private SkuDataOnDemand SkuIntegrationTest.dod;
    
    @Test
    public void SkuIntegrationTest.testCountSkus() {
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", dod.getRandomSku());
        long count = Sku.countSkus();
        Assert.assertTrue("Counter for 'Sku' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SkuIntegrationTest.testFindSku() {
        Sku obj = dod.getRandomSku();
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sku' failed to provide an identifier", id);
        obj = Sku.findSku(id);
        Assert.assertNotNull("Find method for 'Sku' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Sku' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SkuIntegrationTest.testFindAllSkus() {
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", dod.getRandomSku());
        long count = Sku.countSkus();
        Assert.assertTrue("Too expensive to perform a find all test for 'Sku', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Sku> result = Sku.findAllSkus();
        Assert.assertNotNull("Find all method for 'Sku' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Sku' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SkuIntegrationTest.testFindSkuEntries() {
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", dod.getRandomSku());
        long count = Sku.countSkus();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Sku> result = Sku.findSkuEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Sku' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Sku' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SkuIntegrationTest.testFlush() {
        Sku obj = dod.getRandomSku();
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sku' failed to provide an identifier", id);
        obj = Sku.findSku(id);
        Assert.assertNotNull("Find method for 'Sku' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySku(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Sku' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SkuIntegrationTest.testMergeUpdate() {
        Sku obj = dod.getRandomSku();
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sku' failed to provide an identifier", id);
        obj = Sku.findSku(id);
        boolean modified =  dod.modifySku(obj);
        Integer currentVersion = obj.getVersion();
        Sku merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Sku' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SkuIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", dod.getRandomSku());
        Sku obj = dod.getNewTransientSku(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Sku' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Sku' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Sku' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SkuIntegrationTest.testRemove() {
        Sku obj = dod.getRandomSku();
        Assert.assertNotNull("Data on demand for 'Sku' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Sku' failed to provide an identifier", id);
        obj = Sku.findSku(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Sku' with identifier '" + id + "'", Sku.findSku(id));
    }
    
}
