// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ingenuity.salesquote.domain;

import com.ingenuity.salesquote.domain.SalesOrder;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SalesOrder_Roo_Configurable {
    
    declare @type: SalesOrder: @Configurable;
    
}
